let cachedSecret: Uint8Array | undefined;

/** JWT signing secret (Section 11 env vars, `JWT_SIGNING_SECRET`) — generated by the installer
 * at deployment time and stored only as a Vercel environment variable (Section 16.1).
 *
 * The env var is stored as a base64url string (44 chars = 32 random bytes). We decode it back
 * to raw bytes so jose uses all 256 bits of entropy, not the UTF-8 byte sequence of the
 * base64url representation (which would be 44 bytes of ASCII, lower entropy per byte). */
export function getJwtSigningSecret(): Uint8Array {
  if (cachedSecret) {
    return cachedSecret;
  }
  const raw = process.env["JWT_SIGNING_SECRET"];
  if (!raw) {
    throw new Error("JWT_SIGNING_SECRET is not configured in the environment");
  }
  // Decode from base64url (set by step05SetEnv via toBase64Url(32 random bytes)).
  // Fall back to UTF-8 encode if the value is not valid base64url (e.g. a legacy
  // plain-text secret set manually), so existing deployments don't break.
  const base64urlPattern = /^[A-Za-z0-9\-_]+$/;
  if (base64urlPattern.test(raw)) {
    // Decode base64url → raw 32-byte key material
    const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
    const byteLength = Math.floor((raw.length * 6) / 8);
    const bytes = new Uint8Array(byteLength);
    let bitBuffer = 0;
    let bitCount = 0;
    let byteIndex = 0;
    for (const ch of raw) {
      const value = chars.indexOf(ch);
      if (value === -1) {
        throw new Error(
          `Invalid base64url character in JWT_SIGNING_SECRET: '${ch}' (char code ${ch.charCodeAt(0)}). ` +
          `Expected only [A-Za-z0-9-_].`
        );
      }
      bitBuffer = (((bitBuffer << 6) >>> 0) | value) >>> 0;
      bitCount += 6;
      if (bitCount >= 8) {
        bitCount -= 8;
        bytes[byteIndex++] = (bitBuffer >>> bitCount) & 0xff;
      }
    }
    cachedSecret = bytes;
  } else {
    cachedSecret = new TextEncoder().encode(raw);
  }
  return cachedSecret;
}

export function resetJwtSigningSecretForTesting(): void {
  cachedSecret = undefined;
}
